services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    container_name: grapher-db
    ports:
      - 14145:27017
    volumes:
      - ./mongodb/data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      mongo:
        condition: service_started
    ports:
      - 18081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017
      ME_CONFIG_BASICAUTH: "false"
    container_name: grapher-mongo-express

volumes:
  mongo_data:
    driver: local

networks:
  default:
    name: grapher-db
